# Generated by Django 4.2.11 on 2024-03-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querydetail',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='querydetail',
            name='querydatetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
